/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.Database;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.AnimalFactory;
import model.Domba;
import model.Kambing;
import model.Sapi;

/**
 *
 * @author Lenovo
 */
public class BeliPanel extends javax.swing.JPanel {

    /**
     * Creates new form BeliPanel
     */
    public BeliPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupJenisHewan = new javax.swing.ButtonGroup();
        btnGroupJenisKelamin = new javax.swing.ButtonGroup();
        panelKanan1 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        panelSapi1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        isKambing = new javax.swing.JRadioButton();
        isDomba = new javax.swing.JRadioButton();
        isJantan = new javax.swing.JRadioButton();
        isBetina = new javax.swing.JRadioButton();
        isSapi = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        beratSpinner = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBeriVaksin2 = new javax.swing.JButton();

        panelKanan1.setBackground(new java.awt.Color(204, 255, 255));
        panelKanan1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        title1.setBackground(new java.awt.Color(255, 255, 255));
        title1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 153, 153));
        title1.setText("Beli");

        panelSapi1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Jenis Kelamin");

        isKambing.setBackground(new java.awt.Color(204, 255, 255));
        btnGroupJenisHewan.add(isKambing);
        isKambing.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        isKambing.setForeground(new java.awt.Color(51, 51, 51));
        isKambing.setText(" k a m b i n g");
        isKambing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isKambingActionPerformed(evt);
            }
        });

        isDomba.setBackground(new java.awt.Color(204, 255, 255));
        btnGroupJenisHewan.add(isDomba);
        isDomba.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        isDomba.setForeground(new java.awt.Color(51, 51, 51));
        isDomba.setText(" d o m b a");
        isDomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isDombaActionPerformed(evt);
            }
        });

        isJantan.setBackground(new java.awt.Color(204, 255, 255));
        btnGroupJenisKelamin.add(isJantan);
        isJantan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        isJantan.setForeground(new java.awt.Color(51, 51, 51));
        isJantan.setText("jantan");
        isJantan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isJantanActionPerformed(evt);
            }
        });

        isBetina.setBackground(new java.awt.Color(204, 255, 255));
        btnGroupJenisKelamin.add(isBetina);
        isBetina.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        isBetina.setForeground(new java.awt.Color(51, 51, 51));
        isBetina.setText("betina");
        isBetina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isBetinaActionPerformed(evt);
            }
        });

        isSapi.setBackground(new java.awt.Color(204, 255, 255));
        btnGroupJenisHewan.add(isSapi);
        isSapi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        isSapi.setForeground(new java.awt.Color(51, 51, 51));
        isSapi.setText(" s a p i");
        isSapi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        isSapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isSapiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Berat");

        beratSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        beratSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 10, null, 1));
        beratSpinner.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Harga");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Rp");

        btnBeriVaksin2.setBackground(new java.awt.Color(0, 153, 153));
        btnBeriVaksin2.setForeground(new java.awt.Color(255, 255, 255));
        btnBeriVaksin2.setText("B E L I");
        btnBeriVaksin2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBeriVaksin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeriVaksin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSapi1Layout = new javax.swing.GroupLayout(panelSapi1);
        panelSapi1.setLayout(panelSapi1Layout);
        panelSapi1Layout.setHorizontalGroup(
            panelSapi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSapi1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSapi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBeriVaksin2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(panelSapi1Layout.createSequentialGroup()
                        .addComponent(isSapi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(isKambing)
                        .addGap(18, 18, 18)
                        .addComponent(isDomba))
                    .addGroup(panelSapi1Layout.createSequentialGroup()
                        .addGroup(panelSapi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSapi1Layout.createSequentialGroup()
                                .addComponent(isJantan, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panelSapi1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)))
                        .addComponent(isBetina, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(beratSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        panelSapi1Layout.setVerticalGroup(
            panelSapi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSapi1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSapi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isKambing)
                    .addComponent(isDomba)
                    .addComponent(isSapi))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSapi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isJantan)
                    .addComponent(isBetina))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beratSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnBeriVaksin2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelKanan1Layout = new javax.swing.GroupLayout(panelKanan1);
        panelKanan1.setLayout(panelKanan1Layout);
        panelKanan1Layout.setHorizontalGroup(
            panelKanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKanan1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelKanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKanan1Layout.createSequentialGroup()
                        .addComponent(panelSapi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelKanan1Layout.createSequentialGroup()
                        .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(790, 790, 790))))
        );
        panelKanan1Layout.setVerticalGroup(
            panelKanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKanan1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title1)
                .addGap(27, 27, 27)
                .addComponent(panelSapi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void isKambingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isKambingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isKambingActionPerformed

    private void isDombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isDombaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isDombaActionPerformed

    private void isJantanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isJantanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isJantanActionPerformed

    private void isBetinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isBetinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isBetinaActionPerformed

    private void isSapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isSapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isSapiActionPerformed

    private void btnBeriVaksin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeriVaksin2ActionPerformed
        // TODO add your handling code here:
        int berat = (Integer) beratSpinner.getValue();
        String jk;
        
        if(isJantan.isSelected()){
            jk = "jantan";
        } else {
            jk = "betina"; 
        }
        
        try {
            if(isSapi.isSelected()){
                Sapi tempSapi = (Sapi) AnimalFactory.addFromBuying("sapi", jk, berat); 
                Database.getInstance().insertSapi(tempSapi);
                JOptionPane.showMessageDialog(this, "Sukses Tersimpan");

            } else if(isKambing.isSelected()){
                Kambing tempKambing = (Kambing) AnimalFactory.addFromBuying("kambing", jk, berat); 
                Database.getInstance().insertKambing(tempKambing);
                JOptionPane.showMessageDialog(this, "Sukses Tersimpan");

            } else {
                Domba tempDomba = (Domba) AnimalFactory.addFromBuying("domba", jk, berat); 
                Database.getInstance().insertDomba(tempDomba);
                JOptionPane.showMessageDialog(this, "Sukses Tersimpan");
            }
        } catch (SQLException ex) {
            System.err.println(ex);
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Gagal", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBeriVaksin2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner beratSpinner;
    private javax.swing.JButton btnBeriVaksin2;
    private javax.swing.ButtonGroup btnGroupJenisHewan;
    private javax.swing.ButtonGroup btnGroupJenisKelamin;
    private javax.swing.JRadioButton isBetina;
    private javax.swing.JRadioButton isDomba;
    private javax.swing.JRadioButton isJantan;
    private javax.swing.JRadioButton isKambing;
    private javax.swing.JRadioButton isSapi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelKanan1;
    private javax.swing.JPanel panelSapi1;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
